from .auth_view import *
from .dashboard_view import *
from .program_view import *
from .category_view import *
from .chat_view import *
from .testimonials_view import *
from .certificate_view import *
from .enquiry_view import *
from .carousel_view import *
from .student_view import *
from .student_certificate_view import *
from .contact_view import *
from .gallery_view import *
from .notification_view import *
